title: ccccc
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://ha-eunyu.github.io/ccccc

aux_links:
  Template Repository: https://github.com/Ha-eunYu/ccccc.git
